#!/bin/bash
# =========================================================================
# FoodNet Trends Emergency Dashboard Creator
# =========================================================================
#
# Purpose:
#   Creates an emergency fallback dashboard in case the dashboard generation
#   process fails in the pipeline.
#
# Usage:
#   ./emergency_dashboard.sh [output_directory] [project_id]
#
# =========================================================================

OUTPUT_DIR=${1:-"output"}
PROJECT_ID=${2:-$(date +%Y%m%d_%H%M%S)}
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR/$PROJECT_ID"

# Create dashboard files with different naming patterns
DASHBOARD_MAIN="$OUTPUT_DIR/$PROJECT_ID/${PROJECT_ID}_dashboard.html"
DASHBOARD_TIMESTAMP="$OUTPUT_DIR/$PROJECT_ID/${TIMESTAMP}_dashboard.html"

echo "Creating emergency dashboard files:"
echo " - $DASHBOARD_MAIN"
echo " - $DASHBOARD_TIMESTAMP"

# Create dashboard HTML
DASHBOARD_HTML=$(cat <<EOF
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>FoodNet Trends Emergency Dashboard</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    .warning {
      background-color: #f8d7da;
      border: 1px solid #f5c6cb;
      color: #721c24;
      padding: 15px;
      border-radius: 5px;
      margin: 20px 0;
    }
    h1 {
      color: #0054ad;
      border-bottom: 1px solid #ccc;
      padding-bottom: 10px;
    }
    .info {
      background-color: #e2f0fb;
      border: 1px solid #bee5eb;
      color: #0c5460;
      padding: 15px;
      border-radius: 5px;
      margin: 20px 0;
    }
  </style>
</head>
<body>
  <h1>FoodNet Trends Emergency Dashboard</h1>
  
  <div class="warning">
    <h2>⚠️ Dashboard Generation Failed</h2>
    <p>The normal dashboard generation process failed to complete. This is an automatically generated emergency fallback dashboard.</p>
  </div>
  
  <div class="info">
    <h3>Analysis Information</h3>
    <p><strong>Project ID:</strong> $PROJECT_ID</p>
    <p><strong>Generated at:</strong> $(date)</p>
    <p><strong>Generated by:</strong> Emergency Dashboard Generator</p>
  </div>
  
  <h3>Next Steps</h3>
  <p>To view the full analysis results:</p>
  <ol>
    <li>Check the output directory for CSV files with incidence rates and other metrics</li>
    <li>Look at PNG files for visualizations</li>
    <li>Check log files for additional information about the analysis</li>
  </ol>
  
  <div class="info">
    <p>For assistance, please contact the pipeline administrator.</p>
  </div>
  
  <hr>
  <p><small>Emergency dashboard created at $(date)</small></p>
</body>
</html>
EOF
)

# Write to both files
echo "$DASHBOARD_HTML" > "$DASHBOARD_MAIN"
echo "$DASHBOARD_HTML" > "$DASHBOARD_TIMESTAMP"

# Create a symlink for any other potential naming patterns
ln -sf "$DASHBOARD_MAIN" "$OUTPUT_DIR/$PROJECT_ID/dashboard.html"

# Verify files were created
if [ -f "$DASHBOARD_MAIN" ] && [ -f "$DASHBOARD_TIMESTAMP" ]; then
  echo "Success! Emergency dashboard files created."
  echo "Files sizes:"
  ls -lh "$DASHBOARD_MAIN" "$DASHBOARD_TIMESTAMP"
else
  echo "Error: Failed to create dashboard files."
  exit 1
fi